agromap/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
#from ajax_select import urls as ajax_select_urls

#from .views import index, connexion, loggout
#from mon_ghs.views import index, connexion, loggout

admin.site.site_header = "BIENVENUS SUR AGROMAP-Traçability"
admin.site.index_title = "ADMINISTRATION AGROMAP-Traçability"

urlpatterns = [
    path('clients/', include('chocolotiers.urls')),
    #path("select2/", include("django_select2.urls")),
    path('cooperatives/', include('cooperatives.urls')),    
    # path('ajax_select/', include(ajax_select_urls)),
    path('', include('parametres.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cooperatives/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from .views import (
    coop_dashboard,
    add_section,
    add_sous_section,
    producteurs,
    cooperative,
    prod_update,
    prod_delete,
    parcelles,
    parcelle_delete,
    planting,
    planting_update,
    formation,
    detail_formation,
    localisation,
    # use Ajax and jquery request
    my_section,
    export_producteur_csv,
    export_prod_xls,
    export_parcelle_xls,
    export_plant_xls,
    # load_section
)

app_name='cooperatives'

urlpatterns = [
    # Patient
    path('cooperative/<int:id>', cooperative, name='cooperative'),
    path('producteur/<str:code>/modifier', prod_update, name='modifier'),
    path('producteur/<str:code>/supprimer', prod_delete, name='del_producteur'),
    path('parcelle/<int:id>', parcelle_delete, name='del_parcelle'),
    path('dashboard/', coop_dashboard, name='dashboard'),
    path('sections/', add_section, name='section'),
    path('sous_sections/', add_sous_section, name='sous_sections'),
    path('formation/', formation, name='formations'),
    path('formation/<int:id>', detail_formation, name='formation'),
    path('producteurs/', producteurs, name='producteurs'),
    path('parcelles/', parcelles, name='parcelles'),
    path('plantings/', planting, name='planting'),
    path('localisation/', localisation, name='localisation'),
    path('plantings/<int:id>', planting_update, name='planting_update'),

    #get Ajax Data
    #path('my-section/', my_section, name='my_section'),
    # path('ajax/load-section/', load_section, name='ajax_load_section'),

    #Exportation de Données En Excel
    # path('export/csv/', export_producteur_csv, name='export_producteur_csv'),
    path('producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    path('parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    path('plants/xls/', export_plant_xls, name='export_plant_xls'),

    # path('settings/', profile_setting, name='settings'),
    # path('add_patient/', add_patient, name="add_patient"),
    # path('rdv/', rdv_patient, name="checkout"),
]

cooperatives/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import time
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
import datetime

from django.urls import reverse
from django.utils.safestring import mark_safe
from sorl.thumbnail import get_thumbnail

from chocolotiers.models import Client


def producteurs_images(self, filename):
    # verification de l'extension
    real_name, extension = os.path.splitext(filename)
    name = str(int(time.time())) + extension
    return "Producteurs/Images/" + self.code + ".jpeg"

def producteurs_documents(self, filename):
    # verification de l'extension
    real_name, extension = os.path.splitext(filename)
    name = str(int(time.time())) + extension
    return "Producteurs/Documents/" + self.code


def upload_logo_site(self, filename):
    # verification de l'extension
    real_name, extension = os.path.splitext(filename)
    name = str(int(time.time())) + extension
    return "logos/" + self.code + ".jpeg"

from parametres.models import Region, Activite, Origine, Sous_Prefecture, Projet, Espece

TYPE_PRODUCTEUR = (
    ('membre', "MEMBRE"),
    ('usager', "USAGER"),
    # ('caummunautaire', "COMMUNAUTAIRE"),
)

NATURE_DOC = (
    ('AUCUN', 'AUCUN'),
    ('ATTESTATION', 'ATTESTATION'),
    ('CNI', 'CNI'),
    ('PASSEPORT', 'PASSEPORT'),
    ('SEJOUR', 'CARTE DE SEJOUR'),
    ('CONSULAIRE', 'CARTE CONSULAIRE'),
)

CULTURE = (
    ('anacarde', 'ANACARDE'),
    ('cacao', 'CACAO'),
    ('cafe', 'CAFE'),
    ('coton', 'COTON'),
    ('hevea', 'HEVEA'),
    ('palmier', 'PALMIER A HUILE'),
    ('SOJA', 'SOJA'),
    ('autre', 'AUTRES'),
)

CERTIFICATION = (
    ('utz', 'UTZ'),
    ('ra', 'RA'),
    ('bio', 'BIO'),
    ('projet', 'PROJET'),
    ('autre', 'PROJET'),
)

GENRE = (
    ('H', "HOMME"),
    ('F', "FEMME"),
)

ACQUISITION = (
    ('heritage', 'HERITAGE'),
    ('achat', 'ACHAT'),
    ('autres', 'AUTRES'),
)

MODEL_AGRO = (
    ("autour", "AUTOUR"),
    ("autour_centre", "AUTOUR & CENTRE"),
)

class Cooperative(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    projet = models.ManyToManyField(Projet)
    sigle = models.CharField(max_length=500)
    activite = models.ForeignKey(Activite, on_delete=models.CASCADE)
    contacts = models.CharField(max_length=50)
    logo = models.ImageField(verbose_name="Logo", upload_to=upload_logo_site, blank=True)
    add_le = models.DateTimeField(auto_now_add=True)
    update_le = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def get_absolute_url(self):
        return reverse('cooperatives:dashboard', kwargs={"id": self.id})

    def get_projet_values(self):
        ret = ''
        # print(self.projet.all())
        for proj in self.projet.all():
            ret = ret + proj.accronyme + ','
        return ret[:-1]

    def __str__(self):
        return '%s' %(self.sigle)
        # return '%s - %s (%s)' %(self.sigle, self.activite, self.get_projet_values())

    def save(self, force_insert=False, force_update=False):
        self.sigle = self.sigle.upper()
        self.user.last_name = self.user.last_name.upper()
        self.user.first_name = self.user.first_name.upper()
        super(Cooperative, self).save(force_insert, force_update)

    class Meta:
        verbose_name_plural = "COOPERATIVES"
        verbose_name = "cooperative"
        ordering = ["sigle"]

    def Logo(self):
        if self.logo:
            return mark_safe('<img src="%s" style="width: 45px; height:45px;" />' % self.logo.url)
        else:
            return "Aucun Logo"

    Logo.short_description = 'Logo'
    # Create your models here.

class Section(models.Model):
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE)
    libelle = models.CharField(max_length=250)
    responsable = models.CharField(max_length=250)
    contacts = models.CharField(max_length=50)
    add_le = models.DateTimeField(auto_now_add=True)
    update_le = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return '%s - (%s)' %(self.libelle, self.cooperative.sigle)

    def save(self, force_insert=False, force_update=False):
        self.libelle = self.libelle.upper()
        self.responsable = self.responsable.upper()
        super(Section, self).save(force_insert, force_update)

    class Meta:
        verbose_name_plural = "SECTIONS"
        verbose_name = "section"
        ordering = ["libelle"]

class Sous_Section(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    libelle = models.CharField(max_length=250)
    responsable = models.CharField(max_length=250)
    contacts = models.CharField(max_length=50)
    add_le = models.DateTimeField(auto_now_add=True)
    update_le = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return '%s - (%s)' %(self.libelle, self.section.libelle)

    def save(self, force_insert=False, force_update=False):
        self.libelle = self.libelle.upper()
        self.responsable = self.responsable.upper()
        super(Sous_Section, self).save(force_insert, force_update)

    class Meta:
        verbose_name_plural = "SOUS SECTIONS"
        verbose_name = "sous section"
        ordering = ["libelle"]

class Producteur(models.Model):
    code = models.CharField(max_length=150, blank=True, null=True, verbose_name='CODE PRODUCTEUR')
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE)
    origine = models.ForeignKey(Origine, on_delete=models.CASCADE)
    sous_prefecture = models.ForeignKey(Sous_Prefecture, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    sous_section = models.ForeignKey(Sous_Section, related_name="sous_section", on_delete=models.SET_NULL, null=True)
    type_producteur = models.CharField(max_length=50, verbose_name="TYPE PRODUCTEUR", choices=TYPE_PRODUCTEUR, default="membre")
    genre = models.CharField(max_length=2, choices=GENRE, default="H")
    nom = models.CharField(max_length=250, blank=True, null=True)
    prenoms = models.CharField(max_length=500,  blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    contacts = models.CharField(max_length=50, blank=True, null=True)
    localite = models.CharField(max_length=100, blank=True, null=True, verbose_name="LOCALITE")
    nb_enfant = models.PositiveIntegerField(default=0, null=True, blank=True)
    nb_parcelle = models.PositiveIntegerField(default=0)
    image = models.ImageField(verbose_name="Logo", upload_to=producteurs_images, blank=True)
    type_document = models.CharField(max_length=50, verbose_name="TYPE DOCUMENT", choices=NATURE_DOC, default="AUCUN")
    num_document = models.CharField(max_length=150, verbose_name="N° PIECE", null=True, blank=True)
    document = models.FileField(verbose_name="Documents", upload_to=producteurs_documents, blank=True, null=True)
    # add_le = models.DateTimeField(auto_now_add=True)
    # update_le = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return '(%s)-%s %s' %(self.id, self.nom, self.prenoms)

    def Producteur(self):
        return '%s %s' % (self.nom, self.prenoms)

    def clean(self):
        if self.type_document != "AUCUN" and self.document == "":
            raise ValidationError('Veuillez Charger le Document Approprié SVP')
        # numerotation automatique
        # if not self.id:
        #     tot = Producteur.objects.count()
        #     num = tot + 1
        #     #zcode = num.zfill(3)
        #     if not self.code:
        #         self.code = "00%s" % (num)
        #     else:
        #         pass
            # self.code = "%s-%s" % (numero, datetime.date.strftime(madate, '%d/%m/%Y'))

    #def save(self, force_insert=False, force_update=False):
        # self.code = self.code.upper()
        #self.nom = self.nom.upper()
        #self.prenoms = self.prenoms.upper()
        # if self.localite:
        #     self.localite = self.localite.upper()
    #    super(Producteur, self).save(force_insert, force_update)

    def Photo(self):
        if self.image:
            photoLink = "/media/%s" % self.image
            thumb = mark_safe('<img src="%s" style="width: 45px; height:45px;" />' % self.image.url)
            return "<img src='%s' />" % thumb.url
        elif self.genre == "H":
            thumb = mark_safe('<img src="127.0.0.1:8000/static/img/logo_homme.jpeg" style="width: 45px; height:45px;" />')
            # thumb = get_thumbnail('127.0.0.1:8000/static/img/logo_home.jpeg', "60x60", crop='center', quality=99)
            return "<img src='%s' />" % thumb
            # return ""
        else:
            thumb = mark_safe('<img src="127.0.0.1:8000/static/img/logo_femme.jpeg" style="width: 45px; height:45px;" />')
            return "<img src='%s' />" % thumb
            # return "127.0.0.1:8000/img/avatar3.png"
            # return "Aucun logo"

    Photo.short_description = "Logo"
    Photo.allow_tags = True

    class Meta:
        verbose_name_plural = "PRODUCTEURS"
        verbose_name = "producteur"
        ordering = ["id"]

class Parcelle(models.Model):
    code = models.CharField(max_length=150, blank=True, null=True, verbose_name='CODE PARCELLE', help_text="LE CODE PARCELLE EST GENERE AUTOMATIQUEMENT")
    producteur = models.ForeignKey(Producteur, on_delete=models.CASCADE)
    # section = models.ForeignKey(Section, on_delete=models.CASCADE)
    # projet = models.ForeignKey(Projet, on_delete=models.CASCADE)
    sous_section = models.ForeignKey(Sous_Section, related_name="sous_section_parcelle", on_delete=models.SET_NULL, null=True)

templates/Coop/admin_coop_nav.html
{% load static %}

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'accueil' %}">PANNEAU D'ADMINISTRATION</a>
    </div>

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <ul class="nav navbar-right navbar-top-links">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Déconnexion</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
    <!-- /.navbar-top-links -->
    {% include 'Coop/admin_coop_sidebar.html' %}
</nav>

templates/Coop/admin_coop_sidebar.html
{% load static %}
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="{% url 'detail_coop' cooperative.id %}" class="active"><i class="fa fa-dashboard fa-fw"></i> DASHBOARD</a>
            </li>
{#            <li>#}
{#                <a href="{% url 'section_coop' cooperative.id %}"><i class="fa fa-list fa-fw"></i> Sections</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="{% url 'sous_section_coop' cooperative.id %}"><i class="fa fa-list-ol fa-fw"></i> Sous Sections</a>#}
{#            </li>#}
            <li>
                <a href="{% url 'prod_coop' cooperative.id %}"><i class="fa fa-users fa-fw"></i> PRODUCTEURS</a>
            </li>
            <li>
                <a href="{% url 'parcelle_coop' cooperative.id %}"><i class="glyphicon glyphicon-grain"></i> PARCELLES</a>
            </li>
            <li>
                <a href="{% url 'planting_coop' cooperative.id %}"><i class="glyphicon glyphicon-tree-deciduous"></i> PLANTING</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-balance-scale fa-fw"></i> CHARGEMENT PRODUITS</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-truck fa-fw"></i> LIVRAISON PRODUITS</a>
            </li>
            <li>
                <a href="{% url 'localisation_coop' cooperative.id %}" target="_blank"><i class="fa fa-map-o fa-fw"></i> CARTOGRAPHIE</a>
            </li>
        </ul>
    </div>
</div>

templates/Coop/coop_parcelle.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block title %}
    Parcelles |
{% endblock %}
{% block content %}
    <div id="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    {% if user.is_authenticated %}
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'accueil' %}">{{ cooperative.sigle }} / {{ cooperative.get_projet_values }}</a>
        </div>
    {% endif %}

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <ul class="nav navbar-right navbar-top-links">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Déconnexion</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
    <!-- /.navbar-top-links -->
    {% include 'cooperatives/coop_sidebar.html' %}
</nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Parcelles - {{ cooperative.sigle }}</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <div class="row">
                    <div class="col-sm-6 offset-3">
                        {% include '_partials/messages_display.html' %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <i class="fa fa-users fa-fw"></i> Liste des Parcelles
                                <a href="{% url 'cooperatives:export_parcelle_xls' %}" class="btn btn-success">Exporter En Excel</a>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body" style="font-size: 12px">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th>CODE</th>
                                                <th>PROJET</th>
                                                <th>PRODUCTEUR</th>
                                                <th>CERTIFICATION</th>
                                                <th>CULTURE</th>
                                                <th>SUPERFICIE (Ha)</th>
                                                <th>LON</th>
                                                <th>LAT</th>
                                                <th>SECTION</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for parcelle in coop_parcelles %}
                                                <tr class="odd gradeX">
                                                    <td class="center">{{ parcelle.code }}</td>
                                                    <td class="center">{{ parcelle.projet.accronyme }}</td>
                                                    <td class="center">{{ parcelle.producteur }}</td>
                                                    <td class="center">{{ parcelle.certification|upper }}</td>
                                                    <td>{{ parcelle.culture|upper }}</td>
                                                    <td class="center">{{ parcelle.superficie }}</td>
                                                    <td class="center">{{ parcelle.longitude }}</td>
                                                    <td class="center">{{ parcelle.latitude }}</td>
                                                    <td class="center">{{ parcelle.producteur.section }}</td>
                                                    <td class="center">
                                                        <a href="{% url 'cooperatives:del_parcelle' parcelle.code %}" class="btn btn-danger btn-xs">
                                                            <i class="fa fa-trash fa-fw"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-8 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->

{#            <div class="modal fade"  data-keyboard="false" data-backdrop="static" id="ParcelleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{#                <div class="modal-dialog modal-lg" role="document">#}
{#                    <div class="modal-content">#}
{#                        <form method="post" enctype="multipart/form-data">#}
{#                            {% csrf_token %}#}
{#                            <div class="modal-header">#}
{#                                <h4 class="modal-title" id="exampleModalLabel" style="font-weight:bold">AJOUTER NOUVELLE PARCELLE</h4>#}
{#                                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -25px">x</button>#}
{#                            </div>#}
{#                            <div class="model-body">#}
{#                                <div class="col-sm-12">#}
{#                                    {{ parcelleForm.media }}#}
{#                                    <div class="row">#}
{#                                        <div class="col-sm-6">#}
{#                                            <div class="form-group">#}
{#                                                <label>Propriétaire</label>#}
{#                                                {% render_field parcelleForm.producteur class="form-control" %}#}
{#                                                <select name="producteur" placeholder="Producteur" class="form-control" id="id_producteur">#}
{#                                                    {% for prod in producteurs %}#}
{#                                                        <option value="{{ prod.pk }}">{{ prod.code }} {{ prod.nom }} {{ prod.prenoms }}</option>#}
{#                                                    {% endfor %}#}
{#                                                </select>#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>Section</label>#}
{#                                                {% render_field parcelleForm.section class="form-control" %}#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>Sous Section</label>#}
{#                                                {% render_field parcelleForm.sous_section class="form-control" %}#}
{#                                            </div>#}
{#                                            <div class="row">#}
{#                                                <div class="col-sm-6">#}
{#                                                    <div class="form-group">#}
{#                                                        <label>SUPERFICIE</label>#}
{#                                                        {% render_field parcelleForm.superficie class="form-control" placeholder="Longitude" %}#}
{#                                                    </div>#}
{#                                                </div>#}
{#                                                <div class="col-sm-6">#}
{#                                                    <div class="form-group">#}
{#                                                        <label>ACQUISITION</label>#}
{#                                                        {% render_field parcelleForm.acquisition class="form-control" placeholder="Latitude" %}#}
{#                                                    </div>#}
{#                                                </div>#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>LATITUDE</label>#}
{#                                                {% render_field parcelleForm.latitude class="form-control" placeholder="Latitude" %}#}
{#                                            </div>#}
{#                                        </div>#}
{#                                        <div class="col-sm-6">#}
{#                                            <div class="form-group">#}
{#                                                <label>PROJET</label>#}
{#                                                {% render_field parcelleForm.projet class="form-control" placeholder="Acquisition" %}#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>CULTURE</label>#}
{#                                                {% render_field parcelleForm.culture class="form-control" placeholder="Culture" %}#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>CERTIFICATION</label>#}
{#                                                {% render_field parcelleForm.certification class="form-control" placeholder="Certification" %}#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>LONGITUDE</label>#}
{#                                                {% render_field parcelleForm.longitude class="form-control" placeholder="Longitude" %}#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="modal-footer">#}
{#                                <hr />#}
{#                                <Button ID="btnAnnuler" style="font-size:1.7vmin; width:100px" class="btn btn-default"  data-dismiss="modal" >Annuler</Button>#}
{#                                <input type="submit" name="btnValider" value="Valider" id="btnValider" class="btn btn-primary" style="font-size:1.7vmin;width:250px" />#}
{#                            </div>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
        </div>
    </div>
{% endblock %}